export const MAKES: string[] = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "BMW",
  "Bentley",
  "Bugatti",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Datsun",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Jaguar",
  "Jeep",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lotus",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mini",
  "Mitsubishi",
  "Morgan",
  "Nissan",
  "Pagani",
  "Pontiac",
  "Porsche",
  "Rolls-Royce",
  "Subaru",
  "Toyota",
  "Triumph",
  "TVR",
  "Volkswagen",
  "Volvo",
];

export const MODELS_BY_MAKE: Record<string, string[]> = {
  Porsche: [
    "911",
    "912",
    "914",
    "924",
    "928",
    "944",
    "968",
    "964",
    "993",
    "996",
    "997",
    "991",
    "992",
    "Boxster",
    "Cayman",
    "Cayenne",
    "Macan",
    "Panamera",
    "Taycan",
  ],
  BMW: [
    "2002",
    "3 Series",
    "5 Series",
    "7 Series",
    "8 Series",
    "M2",
    "M3",
    "M4",
    "M5",
    "M6",
    "Z3",
    "Z4",
    "Z8",
    "i3",
    "i8",
  ],
  "Mercedes-Benz": [
    "190E",
    "300SL",
    "E-Class",
    "C-Class",
    "S-Class",
    "SL",
    "SLK",
    "AMG GT",
    "G-Class",
  ],
  Ferrari: [
    "308",
    "328",
    "348",
    "355",
    "360",
    "430",
    "458",
    "488",
    "F40",
    "F50",
    "Enzo",
    "California",
    "Roma",
    "SF90",
  ],
  Lamborghini: [
    "Countach",
    "Diablo",
    "Murcielago",
    "Gallardo",
    "Aventador",
    "Huracan",
    "Urus",
  ],
  Ford: [
    "Mustang",
    "GT",
    "GT40",
    "F-100",
    "Bronco",
    "Thunderbird",
    "Falcon",
    "Galaxie",
  ],
  Chevrolet: [
    "Corvette",
    "Camaro",
    "Nova",
    "Chevelle",
    "El Camino",
    "Blazer",
    "Bel Air",
  ],
  Toyota: [
    "Supra",
    "2000GT",
    "Land Cruiser",
    "Celica",
    "MR2",
    "86",
    "GR86",
    "Tacoma",
  ],
  Nissan: [
    "GT-R",
    "Skyline",
    "370Z",
    "350Z",
    "240Z",
    "280Z",
    "300ZX",
    "Silvia",
  ],
  Honda: ["NSX", "S2000", "Civic", "Accord", "Prelude", "Beat"],
  Mazda: ["Miata", "RX-7", "RX-8", "Cosmo", "3", "6", "CX-5"],
  Jaguar: ["E-Type", "XJ", "XK", "F-Type", "XJS", "Mark II"],
  Audi: ["R8", "TT", "Quattro", "A4", "S4", "RS4", "A6", "S6", "RS6", "Q5"],
  Dodge: ["Viper", "Challenger", "Charger", "Dart", "Coronet"],
};
